import Head from 'next/head';
import Image from 'next/image';
import smoke from '../public/smoke.png';
import search from '../public/search.png';
export default function Home() {
  return (
    <div>
      <Head>
        <title>SmokeBnb - Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="max-w-screen-2xl h-12 flex flex-col md:flex-row justify-between m-4 md:mx-20 my-8">
          <div className="flex flex-row gap-2 my-auto">
            <Image
              src={smoke}
              width={32}
              height={32}
              alt="smokebnb-logo"
              style={{
                objectFit: 'contain',
              }}
            />
            <span className="text-xl font-semibold whitespace-nowrap dark:text-primary">smokebnb</span>
          </div>
          <div className="inline-flex rounded-lg shadow-md divide-x divide-gray" role="group">
            <button type="button" className="font-semibold rounded-l-lg py-2 px-4">
              <span className="text-sm text-black">Add location</span>
            </button>
            <button type="button" className=" font-semibold rounded-none py-2 px-4">
              <span className="text-sm text-black text-center">Add guests</span>
            </button>
            <button type="button" className="font-semibold rounded-r-lg py-2 px-4">
              <Image src={search} width={24} height={24} alt="search-icon" />
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
